# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "AI-powered software delivery agent"
  homepage "https://github.com/Inventeer/apex"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.3.0/apex_0.3.0_darwin_amd64.tar.gz"
      sha256 "76b20e63b8e4ee7c442e74d2ea58433364969ad6ce2c77f862b2762e2e6346d7"

      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.3.0/apex_0.3.0_darwin_arm64.tar.gz"
      sha256 "8d1d33570f3675751966e29e4e1e9ebe5b1fbc64e081b4f8e0e811b13a1c7165"

      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.3.0/apex_0.3.0_linux_amd64.tar.gz"
      sha256 "e98ce9bfc4283e705ec84a4ece83af172bea90e1921fb8e9bfc1e95f556c10ae"
      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.3.0/apex_0.3.0_linux_arm64.tar.gz"
      sha256 "3a62dc16f2266dc311bbc7f0288e046c568f297b354984d5e9a5c18c9991fad4"
      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  test do
    system "#{bin}/apex", "version"
  end
end
