# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "AI-powered software delivery agent"
  homepage "https://github.com/Inventeer/apex"
  version "0.2.42"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.42/apex_0.2.42_darwin_amd64.tar.gz"
      sha256 "2deb5cc708d0a416cdbd1342e6371ed27fe3b9cd728514ad89c1dd4bf29eb8cc"

      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.42/apex_0.2.42_darwin_arm64.tar.gz"
      sha256 "44866b14b97747458ba6b80370403590ee7d351a2913f05e6cfbf74b1a48d0d2"

      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.42/apex_0.2.42_linux_amd64.tar.gz"
      sha256 "ff612682cfde3ced26fade9f8b6601caa00b4e7a8d4fe790b16356a4fa841a29"
      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.42/apex_0.2.42_linux_arm64.tar.gz"
      sha256 "7969e35953d2dd145808656b46ded2863b4771076f0aaa7c94fd2fed248065b8"
      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  test do
    system "#{bin}/apex", "version"
  end
end
