# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "AI-powered software delivery agent"
  homepage "https://github.com/Inventeer/apex"
  version "0.2.38"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.38/apex_0.2.38_darwin_amd64.tar.gz"
      sha256 "a0ff31a4505a2077ec580ee340088be7f9d5b0b643c78f7ca9fe3922cc53e5c3"

      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.38/apex_0.2.38_darwin_arm64.tar.gz"
      sha256 "ffa7a7ad6fa7c771b7cae21d9d5f856ecc56412855fd4dc60692715afc337c34"

      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.38/apex_0.2.38_linux_amd64.tar.gz"
      sha256 "964f7887fee6b6f3116138a84013e5f2c99946a8b3a55a444a0b751c173a34af"
      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.2.38/apex_0.2.38_linux_arm64.tar.gz"
      sha256 "62788f7f6efef323fffc21c8dadba1ce3b456af7e39731dd6084ec612342e535"
      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  test do
    system "#{bin}/apex", "version"
  end
end
